apiVersion: apps/v1
kind: Deployment
metadata:
  name: amf
  labels:
    app: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      containers:
       - name: amf
         image: captnko/amf
         securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
         # to keep running and ready
         command: [ "/bin/bash", "-c", "--" ]
         args:
           - while true;
             do sleep 30;
             done;
     
     
