apiVersion: v1
kind: Pod
metadata:
   name: hss
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.187.3.4\"]"
spec:
   containers:
   - name: hss
     image: captnko/hss
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args:
       - while true;
         do sleep 30;
         done;
     
