apiVersion: v1
kind: Pod
metadata:
   name: pcrf
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.187.3.5\"]"
spec:
   containers:
   - name: pcrf
     image: captnko/pcrf
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args:
       - while true;
         do sleep 30;
         done;
     
