apiVersion: v1
kind: Service
metadata:
  name: cn-service
spec:
  selector:
    app: epc
# type: ClusterIP
  clusterIP: 10.43.0.2
  ports:
  - name: enb
    port: 36412
    protocol: SCTP
  - name: smf
    port: 49338
    protocol: TCP
  - name: hss
    port: 3868
    protocol: TCP
  - name: db
    port: 39454
    protocol: TCP
#    nodePort: 36412
#  - port: 2152
#    protocol: TCP 
#  externalIPs:
#    - 192.186.4.2
