apiVersion: v1
kind: Pod
metadata:
   name: ue
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.187.3.254\"]"
spec:
   containers:
   - name: ue1
     image: captnko/ue-f5g
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
